language: python
install:
  - pip install tox
  - pip install coverage
script:
  - tox
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-django18
    - python: "3.4"
      env: TOXENV=py34-django18
    - python: "3.5"
      env: TOXENV=py35-django18
    - python: "3.6"
      env: TOXENV=py36-django18
    - python: "2.7"
      env: TOXENV=py27-django111
    - python: "3.4"
      env: TOXENV=py34-django111
    - python: "3.5"
      env: TOXENV=py35-django111
    - python: "3.6"
      env: TOXENV=py36-django111
    - python: "3.4"
      env: TOXENV=py34-django20
    - python: "3.5"
      env: TOXENV=py35-django20
    - python: "3.6"
      env: TOXENV=py36-django20
branches:
  only:
    - master
